"""
Alert model for financial crime detection alerts.
"""

from datetime import datetime
from enum import Enum
from sqlalchemy import Column, String, DateTime, Float, JSON, Text, Enum as SQLEnum, ForeignKey, Integer
from sqlalchemy.orm import relationship
from app.core.database import Base
import uuid


class AlertSeverity(str, Enum):
    """Alert severity levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AlertStatus(str, Enum):
    """Alert workflow status."""
    NEW = "new"
    INVESTIGATING = "investigating"
    ESCALATED = "escalated"
    RESOLVED_SAR = "resolved_sar"  # Suspicious Activity Report filed
    RESOLVED_FALSE_POSITIVE = "resolved_false_positive"
    CLOSED = "closed"


class Alert(Base):
    """
    Alert model for financial crime detection and investigation.
    
    Alerts are generated by rules, ML models, or screening systems
    for potential AML, fraud, or compliance violations.
    """
    __tablename__ = "alerts"
    
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    
    # Alert Classification
    alert_type = Column(String(100), nullable=False, index=True)
    category = Column(String(100), index=True)  # aml, fraud, sanctions, etc.
    severity = Column(SQLEnum(AlertSeverity), default=AlertSeverity.MEDIUM, index=True)
    status = Column(SQLEnum(AlertStatus), default=AlertStatus.NEW, index=True)
    
    # Alert Details
    title = Column(String(500), nullable=False)
    description = Column(Text)
    detection_rule = Column(String(200))
    confidence_score = Column(Float, default=0.0)
    
    # Related Entities
    primary_entity_id = Column(String(36), ForeignKey("entities.id"), index=True)
    related_entity_ids = Column(JSON, default=list)
    related_transaction_ids = Column(JSON, default=list)
    
    # Risk Assessment
    risk_score = Column(Float, default=0.0, index=True)
    risk_factors = Column(JSON, default=list)
    
    # Investigation
    case_id = Column(String(36), ForeignKey("cases.id"), index=True)
    assigned_to = Column(String(100), index=True)
    investigation_notes = Column(Text)
    
    # Timeline
    detected_at = Column(DateTime, default=datetime.utcnow, index=True)
    acknowledged_at = Column(DateTime)
    resolved_at = Column(DateTime)
    due_date = Column(DateTime)
    
    # Metadata
    source_system = Column(String(100))
    raw_data = Column(JSON, default=dict)
    
    # Audit
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    created_by = Column(String(100))
    updated_by = Column(String(100))
    
    def __repr__(self):
        return f"<Alert {self.id}: {self.title[:50]}>"
    
    def to_dict(self):
        """Convert alert to dictionary."""
        return {
            "id": self.id,
            "alert_type": self.alert_type,
            "category": self.category,
            "severity": self.severity.value if self.severity else None,
            "status": self.status.value if self.status else None,
            "title": self.title,
            "description": self.description,
            "detection_rule": self.detection_rule,
            "confidence_score": self.confidence_score,
            "primary_entity_id": self.primary_entity_id,
            "related_entity_ids": self.related_entity_ids,
            "related_transaction_ids": self.related_transaction_ids,
            "risk_score": self.risk_score,
            "risk_factors": self.risk_factors,
            "case_id": self.case_id,
            "assigned_to": self.assigned_to,
            "investigation_notes": self.investigation_notes,
            "detected_at": self.detected_at.isoformat() if self.detected_at else None,
            "acknowledged_at": self.acknowledged_at.isoformat() if self.acknowledged_at else None,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
            "source_system": self.source_system,
            "created_at": self.created_at.isoformat() if self.created_at else None
        }

